version: "3.8"
  
services:
  db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment: 
      POSTGRES_PASSWORD: 999
      POSTGRES_DB: hermes
      POSTGRES_USER: hermes
