import { Footer } from './Footer'
import { Header } from './Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hermes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col justify-center relative bg-orangel" >
        <Header /> 
        
        <main className="flex flex-col items-center justify-center p-24 bg-orangel">
          {children}         
        </main>

        <Footer />     
      </body>
    </html>
  )
}
